### ISSUE TITLE
Question about  shifted geometric mean

### ISSUE THREAD

**Issue by wind-wind-c** [mattmilten/mittelmann-plots#2]
Can you tell me why use the shifted geometric mean? And why  sh set to 10?

**Comment by mattmilten** [comment]
For some reason, you closed this issue yourself already - I still wanted to reply.
The shifted geometric mean with a shift of 10 is also what Hans uses in his comparisons: [plato.asu.edu/ftp/shgeom.html](http://plato.asu.edu/ftp/shgeom.html)

The shifted geometric mean is a good measure to compare the performance of different solvers and the shift is used to avoid overemphasizing small runtimes too much, e.g., solver A needing 1.5 seconds and solver B needing 4.5 seconds is not as insightful as A needing 100 seconds and B 300 seconds. Although, both comparisons show a 3-fold speedup of A. Adding the shift of 10, we dampen the impact of the first comparison to 11.5 vs. 14.5, so it's only a 1.26 speedup factor that contributes to the overall score.
